### ISSUE TITLE
バイト先のAndroidアプリを完成させる

### ISSUE THREAD

**Issue by YusukeSuzuki1213** [Wild-Family/Milestone#14]
夏休みまでにはリリースする

**Comment by YusukeSuzuki1213** [comment]
- Viewを繰り返し表示する機能について
ListViewではなくRecyclerViewを採用。
RecyclerViewの方がメモリも食わず、柔軟性があるので。
てか、RecyclerViewってListViewを継承してないんだなぁぁ。ListViewの派生かと思ってた。

**Comment by hnkz** [comment]
Kotlinってすげえ良さげな言語やな

**Comment by YusukeSuzuki1213** [comment]
拡張関数とかスコープ関数とかすげぇいい感じ。
シングルトンとかもかきやすい。
少なくともJavaと比較すると

**Comment by YusukeSuzuki1213** [comment]
- データベースの設計について
サロゲートキーとか複合キーとか忘れかけてたので[ここ](https://torazuka.hatenablog.com/entry/20110713/pk)で確認。

**Comment by R-NK** [comment]
> * Viewを繰り返し表示する機能について
>   ListViewではなくRecyclerViewを採用。
>   RecyclerViewの方がメモリも食わず、柔軟性があるので。
>   てか、RecyclerViewってListViewを継承してないんだなぁぁ。ListViewの派生かと思ってた。

ListView，できること少なすぎてちょっとしたレイアウトでもRecyclerView使わないといけなかった気がする

**Comment by YusukeSuzuki1213** [comment]
> > * Viewを繰り返し表示する機能について
> >   ListViewではなくRecyclerViewを採用。
> >   RecyclerViewの方がメモリも食わず、柔軟性があるので。
> >   てか、RecyclerViewってListViewを継承してないんだなぁぁ。ListViewの派生かと思ってた。
> 
> ListView，できること少なすぎてちょっとしたレイアウトでもRecyclerView使わないといけなかった気がする

複

**Comment by YusukeSuzuki1213** [comment]
- いかに品質の高いAndroidアプリを作るか
   - [android-sunflower](https://github.com/googlesamples/android-sunflower)はベストプラクティスをexample appとして公開している(これはJetpackを使ってるのかなぁ)
   - [android-best-practicies-1](https://github.com/shaohui10086/android-best-practices-1)はベストプラクティスを文書で説明している(forkされてるので、情報量が増えてる感あるなぁ)

**Comment by YusukeSuzuki1213** [comment]
- アプリケーションアーキテクチャについて
   - 色々なアーキテクチャがあるなぁ(参考: [android-architecture](https://github.com/googlesamples/android-architecture))
   - うーん、MVVM([Android Architecture Components](https://developer.android.com/topic/libraries/architecture/index.html))にすっか、Googleが推してるし(というか提唱してる)ドキュメントがいい感じにありそう

**Comment by YusukeSuzuki1213** [comment]
- Roomにコルーチンサポートなんかあったのかぁ。推してける。

**Comment by R-NK** [comment]
Android Jetpackだっけ，あれってどうなん

**Comment by YusukeSuzuki1213** [comment]
> Android Jetpackだっけ，あれってどうなん

既存のコードにも「ここだけJetpackの機能使お」みたいなことができちゃうので、入りやすさはある感じ。最近安定版になった、Navigationって機能が画面遷移いい感じにしてくれるらしい。

**Comment by YusukeSuzuki1213** [comment]
- KotlinのSAM変換について
  - KotlinのインターフェースにはSAM変換が使用できない！
```.kt
// Kotlinのインターフェース
interface Hoge {
    fun foo(arg: String): String
}

// KotlinインターフェースをKotlinで実装
val piyo = object: Hoge {
    override fun foo() = "test"
}
```
```.java
// Javaのインターフェース
interface Hoge{
    String foo(String arg);
}

// JavaインターフェースをKotlinで実装
val piyo: Hoge = { "test" }
```
  - 所感
    - Kotlinインターフェースの実装は、overrideするメソッドの処理のコード量が多いと見にくくなりそう
    - そもそもKotlinでSAMは使わない方がいいかも、関数型をクラスに渡してあげるとか
    - 基本的にJavaとの相互運用に使える感じかなぁ

**Comment by YusukeSuzuki1213** [comment]
- LiveDataの[Transformations.switchMap()](https://developer.android.com/reference/android/arch/lifecycle/Transformations.html#switchMap(android.arch.lifecycle.LiveData%3CX%3E,%20android.arch.core.util.Function%3CX,%20android.arch.lifecycle.LiveData%3CY%3E%3E))について
  - triggerの値の変化に応じて、別のLiveDataを流せる
  - 例えばデータベースのテーブルのidによって、任意のカラムを返すなど
  - めんどくさいのは引数のtriggerが複数使えない
    -  [MeditorLiveData](https://developer.android.com/reference/android/arch/lifecycle/MediatorLiveData)を使用して独自に定義しなければならない
    - 具体的には以下のようになる(参考: [MediatorLiveData or switchMap transformation with multiple parameters](https://stackoverflow.com/questions/49493772/mediatorlivedata-or-switchmap-transformation-with-multiple-parameters))
```.kt
class DoubleTrigger<A, B>(a: LiveData<A>, b: LiveData<B>) : MediatorLiveData<Pair<A?, B?>>() {
    init {
        addSource(a) { value = it to b.value }
        addSource(b) { value = a.value to it }
    }
}
```
これでtriggerのどちらかに値の変化があったら、別のLiveDataを流すことができる

**Comment by YusukeSuzuki1213** [comment]
- [Android KTX](https://developer.android.com/kotlin/ktx.html?hl=JA#kotlin)
  - Kotlinのコードをより簡潔に記述できる
  - Jetpackの一部
  - 例: ViewModelで使用するCoroutineScopeが簡潔に書ける
ViewModelにViewModelScopeというCoroutineScope型のプロパティが用意されているおかげで、onClearedでジョブをキャンセルする記述をしなくて済む。
  - その他色々簡潔に書けるようになるので、めちゃ便利

**Comment by YusukeSuzuki1213** [comment]
- 雑記
  - 永遠に外部からのIntent(暗黙的Intent)に反応できない (泣
  - RxJava, AACあれ、まじよくわからん。勉強する。
  - RecyclerViewのスワイプ削除いい感じになった。

**Comment by YusukeSuzuki1213** [comment]
- Intentによるファイルの共有で、ファイルパスが取り出せずつまった
    - URIのスキームが"file://"の場合はuri.getPath()でファイルパスが取得できる("file://"でIntent飛ばしてくんの非推奨だからやめてくれぇ？)
    - "content://"の場合はContentProviderを経由してMediaStoreに対し問い合わせを行い、ファイルパスを取得しなければいけない。uri.getPath()でパスは取得できるが正しいパスじゃない(これまじ紛らわしい)
    - しかしこれでも"content：//"スキームのURIを取得することができない場合がある(アプリに依存)。MediaStoreへ問い合わせてもNULLが返ってくる。これはまじで謎。なのでUri→InputStreamと変換して対処。（すべてのスキームに対してこれをやればよかった？）
    - この他にも、URIがエンコードされて送ってくるアプリがあったりと、バリエーションありすぎた(泣

**Comment by YusukeSuzuki1213** [comment]
- [Google I/O 2019](https://events.google.com/io/)で気になったトピックついての所感
  - [Dark Theme](https://developer.android.com/preview/features/darktheme)への対応
Android Qからダークテーマが追加される。ダークモード対応のアプリ作るのダルいと思ったけどわりと簡単にいけそう(DayNightTheme使うなど)。さらにフォースダーク機能で自動でダークテーマっぽくしてくれる(ダークテーマにしたくないWidgetとかはXMLで指定できる)

  - ViewBinding
Viewアクセスへの新しい方法。Android Studio 3.6から追加される。`findViewById`,DataBinding, ButterKnife, Kotlin Syntheticのそれぞれの問題を解決する。ふーむでも、ぶっちゃけ今回の発表でDataBindingがめちゃくちゃ使いやすくなった(コンパイルの速度があがったり、エラーメッセージが優しくなったり)のでDataBinding使ってけばいい感はある。んー、あぁでも、Viewへのアクセスのみの目的ならViewBinding使ってもいい感はある。使ってみんとわからん。

  - [Jetpack Compose](https://developer.android.com/jetpack/compose)
FlutterみたくコードでUIを書いてく。まだアルファ版も出てないので使わないでとのこと。これ[Anko](https://github.com/Kotlin/anko)となにか違うんけ？Kotlin MPPの布石か？？。

  - [CameraX](https://developer.android.com/training/camerax)
カメラ開発を簡単にできるらしい。Androidでカメラ開発はデバイスごとに対応しなければならず闇があった(やったことないからわからん)。たぶん、オンデバイス化の流れでカメラ機能も使いやすくしたよみたいな？

  - その他
    - めっちゃセキリュティ言うやん
    - [キーノート](https://www.youtube.com/watch?v=lyRPyRKHO8M)の日本語字幕うれしす

**Comment by YusukeSuzuki1213** [comment]
納品した(2019/09/20)

**Comment by R-NK** [comment]
ようやく夏休み始まったな

**Comment by YusukeSuzuki1213** [comment]
完成したためCloseします
