### ISSUE TITLE
Redox Security

### ISSUE THREAD

**Issue by hnkz** [Wild-Family/Milestone#2]
Redoxのセキュリティについてまとめる。
SecHackでやることを、ある程度決める。

## 参考情報
- [redox-os](https://gitlab.redox-os.org/redox-os/redox)

**Comment by hnkz** [comment]
Redoxのビルド通らねえ。
ゴミかよ。

**Comment by R-NK** [comment]
またissue立てて駄々こねよ

**Comment by hnkz** [comment]
XCodeアプデしてる。72 Mbpsだからクソ遅い。

**Comment by hnkz** [comment]
アプデ終わり。さあ、ビルドするぞ。

**Comment by hnkz** [comment]
ビルドできなかった。
Ubuntu入れてビルドしようとしてるけどコケる。うんこ。

**Comment by hnkz** [comment]
やっとビルド通った。長かっタァ

**Comment by hnkz** [comment]
cargo-featuresで色々付け足したらいけた

**Comment by hnkz** [comment]
Dockerの使い方忘れて切れてた

**Comment by hnkz** [comment]
ビルドした。
適当にコード読んだり改変したりする。
Redoxに慣れよう。
