### ISSUE TITLE
自作OS

### ISSUE THREAD

**Issue by hnkz** [Wild-Family/Milestone#6]
xv6の[ソースコード](https://github.com/mit-pdos/xv6-public)と[教科書](https://pdos.csail.mit.edu/6.828/2014/xv6/book-rev8.pdf)を読む。

自作OSをやる

**Comment by hnkz** [comment]
Rustでxv6書いてる[プロジェクト](https://github.com/connorkuehl/xv6-rust)もあった。
面白そ〜

**Comment by hnkz** [comment]
読んでるなう。
inline assembly分からんからそこからやってるお

**Comment by wan-nyan-wan** [comment]
xv6でなんか作った
