### ISSUE TITLE
Donald's journey into the React World

### ISSUE THREAD

**Issue by R-NK** [Wild-Family/Milestone#9]
ドナルドと行く 心躍るReact物見遊山

**Comment by R-NK** [comment]
# First Step
[Tutorial: Intro to React](https://reactjs.org/tutorial/tutorial.html#before-we-start-the-tutorial)を読む

**Comment by R-NK** [comment]
# Second Step (Its a bit longer than you expected)
[Completing the Game](https://reactjs.org/tutorial/tutorial.html#completing-the-game)をやる
[create-react-app](https://github.com/facebook/create-react-app)を使って`yarn create react-app my-app --typescript`でTypeScriptの環境を作成
@typescript-eslintの導入にめちゃくちゃ手こずった(フロントエンドはクソ)
最新のTypeScriptでのコンポーネントの書き方は[react-typescript-cheatsheet](https://github.com/sw-yx/react-typescript-cheatsheet)を参考にした
[完成したやつ](https://github.com/R-NK/react-tutorial-ts)

**Comment by R-NK** [comment]
# Third Step (React meets Electron)
- Second Stepで作ったものをElectronに移植する
- 当初自力でWebpackを書くも、意味不明すぎて挫折
- 最終的に[electron-forge](https://github.com/electron-userland/electron-forge)を使って土台を作成
  - これのメンテナはめちゃくちゃ優しい。俺による俺しか喜ばんようなプルリクをマージしてくれた
- [完成したやつ](https://github.com/R-NK/electron-react-tutorial-ts)
  - electron-forgeがバージョンアップしてないのでローカルモジュールを参照してる
  - [ ] バージョンアップしたら公式を参照するように変える

**Comment by R-NK** [comment]
# Fourth Step (Into the Real World)
- [ ] react-routerでルーティングする
  - MemoryRouterじゃないといけないらしい [(参考)](https://v6.electronforge.io/plugins/webpack#how-do-i-do-virtual-routing)
- [ ] State管理の手法について調査する
  - Redux
    - Fluxを拡張したライブラリ。めんどくさそう
  - Context API
    - Storeパターンを実現するReact公式API。function等のStore以外の機能がない
    - これを拡張した[unstated](https://github.com/jamiebuilds/unstated)がアツいらしい

**Comment by R-NK** [comment]
>   * electron-forgeがバージョンアップしてないのでローカルモジュールを参照してる
> * [ ]  バージョンアップしたら公式を参照するように変える

ローカルモジュールの参照には`yarn link`を使うらしい？

**Comment by R-NK** [comment]
electron-devtools-installerはWindowsで7zのパス解決にバグがあるらしい(MarshallOfSound/electron-devtools-installer#55)
代わりに[electron-load-devtool](https://github.com/akameco/electron-load-devtool)を使う

**Comment by R-NK** [comment]
# Webpack & ESLintメモ
## Webpackのaliasについて
- webpackのaliasを使用する場合，ESLintがunresolveを吐いてしまうので[eslint-import-resolver-webpack](https://www.npmjs.com/package/eslint-import-resolver-webpack)を併用する
  - **aliasに `@` を含んではいけない！** eslint-plugin-importの仕様で外部モジュール扱いされるため。
  - webpack.config.jsはeslintrcと同じ階層にないとダメらしい？

**Comment by R-NK** [comment]
- TypeScriptとreact-hot-loaderを併用する場合は`module.hot`プロパティが見つからないと言われるので`@types/webpack-env`を入れる

**Comment by R-NK** [comment]
## 閑話休題
- [swc](https://github.com/swc-project/swc)
  - Rustで書かれたトランスパイラ。めちゃくちゃ速いらしい
- [Parcel](https://github.com/parcel-bundler/parcel)
  - Webpackのような数千行に渡る設定ファイルが不要なバンドラ。開発中のバージョン2で`electron-forge`でも使えるらしい

**Comment by hnkz** [comment]
Rustで書かれたトランスパイラま？

**Comment by R-NK** [comment]
# But we can't skirt modern-stupid-design tools
- [Adobe XD](https://www.adobe.com/jp/products/xd.html)
  - 一人で使う分にはすべて無料
  - 無料プランでは一つのプロトタイプ、デザインスペックのみ共有可能(人数に制限なし？)
  - チュートリアルが日本語化されており、なおかつ簡潔でわかりやすい
  - ショートカットを含めた操作感は良好
  - Windows環境でクライアントアプリのフレームレートが低いバグが発生
- [figma](https://www.figma.com)
  - 無料プランでは二人まで、かつ3つのプロジェクトまで共有可能
  - チュートリアルがわかりづらい
  - UIの変更が頻繁で実際のUIと公式の説明が食い違っていたりする
  - 流行り、らしい(本当か？)
- [STUDIO](https://studio.design)
  - 無料プランでも無制限に共有可能
  - ドメインを指定してWebサイトを公開できる
  - 操作があまりにもわかりづらい
  - 3人でリアルタイムに同時編集すると巻き戻りや削除不能等バグが多発した

## 所感
- 個人的にはAdobe XDが最もとっつきやすいと感じた
  - フレームレート低下バグは環境依存の可能性大。Webブラウザ上で使う分には問題ない
- コンポーネントやワイヤーフレームの充実度はsketch>figma>Adobe XDの印象
